spring:
  web:
    #静态资源处理
    resources:

      add-mappings: true
      cache:
        cachecontrol:
          max-age: 3600
      #启动默认静态资源处理，默认启用
      chain:
        #资源链启动缓存，默认启动
        cache: true
        #启用资源链，默认禁用
        enabled: true
        #启用压缩资源(gzip,brotli)解析，默认禁用
        compressed: true
      static-locations: classpath:/static/

  resources:
    chain:
      #启用h5应用缓存，默认禁用
      html-application-cache: true

  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    # ?????
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # ?????
      maximum-pool-size: 15
      # ?????
      minimum-idle: 5
      # ????ttl
      idle-timeout: 1800000
      # ??ttl
      max-lifetime: 1800000
      # ?????????????
      auto-commit: true
      # ?????????30000?30??
      connection-timeout: 30000
      # ?????????????
      connection-test-query: SELECT 1
  redis:
    host: 120.25.242.250
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞时间
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

mybatis-plus:
  configuration:
    # ???? log-impl?????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ??????????????
    map-underscore-to-camel-case: true
  # ?xml??????
  type-aliases-package: me.xnmk.seckill.pojo
  # ??xml????
  mapper-locations: classpath:mapper/*.xml